version: '3'

services:
  app:
    container_name: camino_api_docs
    image: caminofr/camino-api-docs
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${PORT}
      LETSENCRYPT_HOST: ${URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      NGINX_PORT: ${PORT}
    expose:
      - ${PORT}
    networks:
      - default
      - nginx-proxy
    restart: always

networks:
  nginx-proxy:
    external: true
